---
# Dependencies other than git submodules are managed by the repository's Renovate configuration.

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    rebase-strategy: disabled
    schedule:
      interval: "cron"
      cronjob: "30 2 * * *"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
