/**
 * @file tests/unit/test_http_pairing.cpp
 * @brief Test src/nvhttp.cpp HTTP pairing process
 */

#include "../tests_common.h"

#include <atomic>
#include <Simple-Web-Server/client_http.hpp>
#include <src/nvhttp.h>
#include <thread>

using namespace nvhttp;

struct pairing_input {
  std::shared_ptr<pair_session_t> session;
  /**
   * Normally server challenge is generated by the server, but for testing purposes
   * we can override it with a custom value. This way the process is deterministic.
   */
  std::string override_server_challenge;
  std::string pin;
  std::string client_challenge;
  std::string server_challenge_resp;
  std::string client_pairing_secret;
};

struct pairing_output {
  bool phase_1_success;
  bool phase_2_success;
  bool phase_3_success;
  bool phase_4_success;
};

const std::string PRIVATE_KEY = R"(-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLePNlWN06FLlM
ujWzIX8UICO7SWfH5DXlafVjpxwi/WCkdO6FxixqRNGu71wMvJXFbDlNR8fqX2xo
+eq17J3uFKn+qdjmP3L38bkqxhoJ/nCrXkeGyCTQ+Daug63ZYSJeW2Mmf+LAR5/i
/fWYfXpSlbcf5XJQPEWvENpLqWu+NOU50dJXIEVYpUXRx2+x4ZbwkH7tVJm94L+C
OUyiJKQPyWgU2aFsyJGwHFfePfSUpfYHqbHZV/ILpY59VJairBwE99bx/mBvMI7a
hBmJTSDuDffJcPDhFF5kZa0UkQPrPvhXcQaSRti7v0VonEQj8pTSnGYr9ktWKk92
wxDyn9S3AgMBAAECggEAbEhQ14WELg2rUz7hpxPTaiV0fo4hEcrMN+u8sKzVF3Xa
QYsNCNoe9urq3/r39LtDxU3D7PGfXYYszmz50Jk8ruAGW8WN7XKkv3i/fxjv8JOc
6EYDMKJAnYkKqLLhCQddX/Oof2udg5BacVWPpvhX6a1NSEc2H6cDupfwZEWkVhMi
bCC3JcNmjFa8N7ow1/5VQiYVTjpxfV7GY1GRe7vMvBucdQKH3tUG5PYXKXytXw/j
KDLaECiYVT89KbApkI0zhy7I5g3LRq0Rs5fmYLCjVebbuAL1W5CJHFJeFOgMKvnO
QSl7MfHkTnzTzUqwkwXjgNMGsTosV4UloL9gXVF6GQKBgQD5fI771WETkpaKjWBe
6XUVSS98IOAPbTGpb8CIhSjzCuztNAJ+0ey1zklQHonMFbdmcWTkTJoF3ECqAos9
vxB4ROg+TdqGDcRrXa7Twtmhv66QvYxttkaK3CqoLX8CCTnjgXBCijo6sCpo6H1T
+y55bBDpxZjNFT5BV3+YPBfWQwKBgQDQyNt+saTqJqxGYV7zWQtOqKORRHAjaJpy
m5035pky5wORsaxQY8HxbsTIQp9jBSw3SQHLHN/NAXDl2k7VAw/axMc+lj9eW+3z
2Hv5LVgj37jnJYEpYwehvtR0B4jZnXLyLwShoBdRPkGlC5fs9+oWjQZoDwMLZfTg
eZVOJm6SfQKBgQDfxYcB/kuKIKsCLvhHaSJpKzF6JoqRi6FFlkScrsMh66TCxSmP
0n58O0Cqqhlyge/z5LVXyBVGOF2Pn6SAh4UgOr4MVAwyvNp2aprKuTQ2zhSnIjx4
k0sGdZ+VJOmMS/YuRwUHya+cwDHp0s3Gq77tja5F38PD/s/OD8sUIqJGvQKBgBfI
6ghy4GC0ayfRa+m5GSqq14dzDntaLU4lIDIAGS/NVYDBhunZk3yXq99Mh6/WJQVf
Uc77yRsnsN7ekeB+as33YONmZm2vd1oyLV1jpwjfMcdTZHV8jKAGh1l4ikSQRUoF
xTdMb5uXxg6xVWtvisFq63HrU+N2iAESmMnAYxRZAoGAVEFJRRjPrSIUTCCKRiTE
br+cHqy6S5iYRxGl9riKySBKeU16fqUACIvUqmqlx4Secj3/Hn/VzYEzkxcSPwGi
qMgdS0R+tacca7NopUYaaluneKYdS++DNlT/m+KVHqLynQr54z1qBlThg9KGrpmM
LGZkXtQpx6sX7v3Kq56PkNk=
-----END PRIVATE KEY-----)";
const std::string PUBLIC_CERT = R"(-----BEGIN CERTIFICATE-----
MIIC6zCCAdOgAwIBAgIBATANBgkqhkiG9w0BAQsFADA5MQswCQYDVQQGEwJJVDEW
MBQGA1UECgwNR2FtZXNPbldoYWxlczESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIy
MDQwOTA5MTYwNVoXDTQyMDQwNDA5MTYwNVowOTELMAkGA1UEBhMCSVQxFjAUBgNV
BAoMDUdhbWVzT25XaGFsZXMxEjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMt482VY3ToUuUy6NbMhfxQgI7tJZ8fkNeVp
9WOnHCL9YKR07oXGLGpE0a7vXAy8lcVsOU1Hx+pfbGj56rXsne4Uqf6p2OY/cvfx
uSrGGgn+cKteR4bIJND4Nq6DrdlhIl5bYyZ/4sBHn+L99Zh9elKVtx/lclA8Ra8Q
2kupa7405TnR0lcgRVilRdHHb7HhlvCQfu1Umb3gv4I5TKIkpA/JaBTZoWzIkbAc
V9499JSl9gepsdlX8guljn1UlqKsHAT31vH+YG8wjtqEGYlNIO4N98lw8OEUXmRl
rRSRA+s++FdxBpJG2Lu/RWicRCPylNKcZiv2S1YqT3bDEPKf1LcCAwEAATANBgkq
hkiG9w0BAQsFAAOCAQEAqPBqzvDjl89pZMll3Ge8RS7HeDuzgocrhOcT2jnk4ag7
/TROZuISjDp6+SnL3gPEt7E2OcFAczTg3l/wbT5PFb6vM96saLm4EP0zmLfK1FnM
JDRahKutP9rx6RO5OHqsUB+b4jA4W0L9UnXUoLKbjig501AUix0p52FBxu+HJ90r
HlLs3Vo6nj4Z/PZXrzaz8dtQ/KJMpd/g/9xlo6BKAnRk5SI8KLhO4hW6zG0QA56j
X4wnh1bwdiidqpcgyuKossLOPxbS786WmsesaAWPnpoY6M8aija+ALwNNuWWmyMg
9SVDV76xJzM36Uq7Kg3QJYTlY04WmPIdJHkCtXWf9g==
-----END CERTIFICATE-----)";

struct PairingTest: BaseTest, testing::WithParamInterface<std::tuple<pairing_input, pairing_output>> {};

TEST_P(PairingTest, Run) {
  auto [input, expected] = GetParam();

  boost::property_tree::ptree tree;

  setup(PRIVATE_KEY, PUBLIC_CERT);

  // phase 1
  getservercert(*input.session, tree, input.pin);
  ASSERT_EQ(tree.get<int>("root.paired") == 1, expected.phase_1_success);
  if (!expected.phase_1_success) {
    return;
  }

  // phase 2
  clientchallenge(*input.session, tree, input.client_challenge);
  ASSERT_EQ(tree.get<int>("root.paired") == 1, expected.phase_2_success);
  if (!expected.phase_2_success) {
    return;
  }

  // phase 3
  serverchallengeresp(*input.session, tree, input.server_challenge_resp);
  ASSERT_EQ(tree.get<int>("root.paired") == 1, expected.phase_3_success);
  if (!expected.phase_3_success) {
    return;
  }
  input.session->serverchallenge = input.override_server_challenge;

  // phase 4
  auto input_client_cert = input.session->client.cert;  // Will be moved
  auto add_cert = std::make_shared<safe::queue_t<crypto::x509_t>>(30);
  clientpairingsecret(*input.session, add_cert, tree, input.client_pairing_secret);
  ASSERT_EQ(tree.get<int>("root.paired") == 1, expected.phase_4_success);

  // Check that we actually added the input client certificate to `add_cert`
  if (expected.phase_4_success) {
    ASSERT_EQ(add_cert->peek(), true);
    auto cert = add_cert->pop();
    char added_subject_name[256];
    X509_NAME_oneline(X509_get_subject_name(cert.get()), added_subject_name, sizeof(added_subject_name));

    auto input_cert = crypto::x509(input_client_cert);
    char original_suject_name[256];
    X509_NAME_oneline(X509_get_subject_name(input_cert.get()), original_suject_name, sizeof(original_suject_name));

    ASSERT_EQ(std::string(added_subject_name), std::string(original_suject_name));
  }
}

INSTANTIATE_TEST_SUITE_P(
  TestWorkingPairing,
  PairingTest,
  testing::Values(
    std::make_tuple(
      pairing_input {
        .session = std::make_shared<pair_session_t>(
          pair_session_t {
            .client = {
              .uniqueID = "1234",
              .cert = PUBLIC_CERT,
              .name = "test"
            },
            .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}
          }
        ),
        .override_server_challenge = util::from_hex_vec("AAAAAAAAAAAAAAAA", true),
        .pin = "5338",
        /* AES("CLIENT CHALLENGE") */
        .client_challenge = util::from_hex_vec("741CD3D6890C16DA39D53BCA0893AAF0", true),
        /* SHA = SHA265(server_challenge + public cert signature + "SECRET  ") = "6493DAE49C913E1AEAF37C1072F71D664B72B2C4DA1FFB4720BECE0D929E008A"
         * AES( SHA ) */
        .server_challenge_resp = util::from_hex_vec("920BABAE9F7599AA1CA8EC87FB3454C91872A7D8D5127DDC176C2FDAE635CF7A", true),
        /* secret + x509 signature */
        .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFF"  // secret
                                                    "9BB74D8DE2FF006C3F47FC45EFDAA97D433783AFAB3ACD85CA7ED2330BB2A7BD18A5B044AF8CAC177116FAE8A6E8E44653A8944A0F8EA138B2E013756D847D2C4FC52F736E2E7E9B4154712B18F8307B2A161E010F0587744163E42ECA9EA548FC435756EDCF1FEB94037631ABB72B29DDAC0EA5E61F2DBFCC3B20AA021473CC85AC98D88052CA6618ED1701EFBF142C18D5E779A3155B84DF65057D4823EC194E6DF14006793E8D7A3DCCE20A911636C4E01ECA8B54B9DE9F256F15DE9A980EA024B30D77579140D45EC220C738164BDEEEBF7364AE94A5FF9B784B40F2E640CE8603017DEEAC7B2AD77B807C643B7B349C110FE15F94C7B3D37FF15FDFBE26",
                                                    true)
      },
      pairing_output {true, true, true, true}
    ),
    // Testing that when passing some empty values we aren't triggering any exception
    std::make_tuple(pairing_input {
                      .session = std::make_shared<pair_session_t>(pair_session_t {.client = {}, .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}}),
                      .override_server_challenge = {},
                      .pin = {},
                      .client_challenge = {},
                      .server_challenge_resp = {},
                      .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFFxDEADBEEF", true),
                    },
                    // Only phase 4 will fail, when we check what has been exchanged
                    pairing_output {true, true, true, false}),
    // Testing that when passing some empty values we aren't triggering any exception
    std::make_tuple(pairing_input {
                      .session = std::make_shared<pair_session_t>(pair_session_t {.client = {.cert = PUBLIC_CERT}, .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}}),
                      .override_server_challenge = {},
                      .pin = {},
                      .client_challenge = {},
                      .server_challenge_resp = {},
                      .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFFxDEADBEEF", true),
                    },
                    // Only phase 4 will fail, when we check what has been exchanged
                    pairing_output {true, true, true, false})
  )
);

INSTANTIATE_TEST_SUITE_P(
  TestFailingPairing,
  PairingTest,
  testing::Values(
    /**
     * Wrong PIN
     */
    std::make_tuple(
      pairing_input {
        .session = std::make_shared<pair_session_t>(
          pair_session_t {
            .client = {
              .uniqueID = "1234",
              .cert = PUBLIC_CERT,
              .name = "test"
            },
            .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}
          }
        ),
        .override_server_challenge = util::from_hex_vec("AAAAAAAAAAAAAAAA", true),
        .pin = "0000",
        .client_challenge = util::from_hex_vec("741CD3D6890C16DA39D53BCA0893AAF0", true),
        .server_challenge_resp = util::from_hex_vec("920BABAE9F7599AA1CA8EC87FB3454C91872A7D8D5127DDC176C2FDAE635CF7A", true),
        .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFF"  // secret
                                                    "9BB74D8DE2FF006C3F47FC45EFDAA97D433783AFAB3ACD85CA7ED2330BB2A7BD18A5B044AF8CAC177116FAE8A6E8E44653A8944A0F8EA138B2E013756D847D2C4FC52F736E2E7E9B4154712B18F8307B2A161E010F0587744163E42ECA9EA548FC435756EDCF1FEB94037631ABB72B29DDAC0EA5E61F2DBFCC3B20AA021473CC85AC98D88052CA6618ED1701EFBF142C18D5E779A3155B84DF65057D4823EC194E6DF14006793E8D7A3DCCE20A911636C4E01ECA8B54B9DE9F256F15DE9A980EA024B30D77579140D45EC220C738164BDEEEBF7364AE94A5FF9B784B40F2E640CE8603017DEEAC7B2AD77B807C643B7B349C110FE15F94C7B3D37FF15FDFBE26",
                                                    true)
      },
      pairing_output {true, true, true, false}
    ),
    /**
     * Wrong client challenge
     */
    std::make_tuple(pairing_input {.session = std::make_shared<pair_session_t>(pair_session_t {.client = {.uniqueID = "1234", .cert = PUBLIC_CERT, .name = "test"}, .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}}), .override_server_challenge = util::from_hex_vec("AAAAAAAAAAAAAAAA", true), .pin = "5338", .client_challenge = util::from_hex_vec("741CD3D6890C16DA39D53BCA0893AAF0", true), .server_challenge_resp = util::from_hex_vec("WRONG", true),
                                   .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFF"  // secret
                                                                               "9BB74D8DE2FF006C3F47FC45EFDAA97D433783AFAB3ACD85CA7ED2330BB2A7BD18A5B044AF8CAC177116FAE8A6E8E44653A8944A0F8EA138B2E013756D847D2C4FC52F736E2E7E9B4154712B18F8307B2A161E010F0587744163E42ECA9EA548FC435756EDCF1FEB94037631ABB72B29DDAC0EA5E61F2DBFCC3B20AA021473CC85AC98D88052CA6618ED1701EFBF142C18D5E779A3155B84DF65057D4823EC194E6DF14006793E8D7A3DCCE20A911636C4E01ECA8B54B9DE9F256F15DE9A980EA024B30D77579140D45EC220C738164BDEEEBF7364AE94A5FF9B784B40F2E640CE8603017DEEAC7B2AD77B807C643B7B349C110FE15F94C7B3D37FF15FDFBE26",
                                                                               true)},
                    pairing_output {true, true, true, false}),
    /**
     * Wrong signature
     */
    std::make_tuple(pairing_input {.session = std::make_shared<pair_session_t>(pair_session_t {.client = {.uniqueID = "1234", .cert = PUBLIC_CERT, .name = "test"}, .async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}}), .override_server_challenge = util::from_hex_vec("AAAAAAAAAAAAAAAA", true), .pin = "5338", .client_challenge = util::from_hex_vec("741CD3D6890C16DA39D53BCA0893AAF0", true), .server_challenge_resp = util::from_hex_vec("920BABAE9F7599AA1CA8EC87FB3454C91872A7D8D5127DDC176C2FDAE635CF7A", true),
                                   .client_pairing_secret = util::from_hex_vec("000102030405060708090A0B0C0D0EFF"  // secret
                                                                               "NOSIGNATURE",  // Wrong signature
                                                                               true)},
                    pairing_output {true, true, true, false}),
    /**
     * null values (phase 1)
     */
    std::make_tuple(pairing_input {.session = std::make_shared<pair_session_t>()}, pairing_output {false}),
    /**
     * null values (phase 4, phase 2 and 3 have no reason to fail since we are running them in order)
     */
    std::make_tuple(pairing_input {.session = std::make_shared<pair_session_t>(pair_session_t {.async_insert_pin = {.salt = "ff5dc6eda99339a8a0793e216c4257c4"}})}, pairing_output {true, true, true, false})
  )
);

TEST(PairingTest, OutOfOrderCalls) {
  boost::property_tree::ptree tree;

  setup(PRIVATE_KEY, PUBLIC_CERT);

  pair_session_t sess {};

  clientchallenge(sess, tree, "test");
  ASSERT_FALSE(tree.get<int>("root.paired") == 1);

  serverchallengeresp(sess, tree, "test");
  ASSERT_FALSE(tree.get<int>("root.paired") == 1);

  auto add_cert = std::make_shared<safe::queue_t<crypto::x509_t>>(30);
  clientpairingsecret(sess, add_cert, tree, "test");
  ASSERT_FALSE(tree.get<int>("root.paired") == 1);

  // This should work, it's the first time we call it
  sess.async_insert_pin.salt = "ff5dc6eda99339a8a0793e216c4257c4";
  getservercert(sess, tree, "test");
  ASSERT_TRUE(tree.get<int>("root.paired") == 1);

  // Calling it again should fail
  getservercert(sess, tree, "test");
  ASSERT_FALSE(tree.get<int>("root.paired") == 1);
}

namespace {
  pair_session_t pending_session(std::string unique_id) {
    pair_session_t session;
    session.client.uniqueID = std::move(unique_id);
    session.async_insert_pin.response = std::shared_ptr<typename SimpleWeb::ServerBase<SimpleWeb::HTTP>::Response> {};
    return session;
  }
}  // namespace

TEST(PairingSessionManagerTest, UsesOpaque128BitRequestIdsAndExplicitSelection) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};

  auto first = manager.add(pending_session("client-a"), "192.0.2.1", {}, now);
  auto second = manager.add(pending_session("client-b"), "192.0.2.2", {}, now);

  ASSERT_TRUE(first);
  ASSERT_TRUE(second);
  EXPECT_EQ(first.request_id.size(), 32U);
  EXPECT_EQ(second.request_id.size(), 32U);
  EXPECT_NE(first.request_id, second.request_id);
  EXPECT_FALSE(manager.find_single_pending(now));

  auto selected = manager.find_pending_by_request_id(second.request_id, now);
  ASSERT_TRUE(selected);
  EXPECT_EQ(selected.unique_id(), "client-b");
}

TEST(PairingSessionManagerTest, LegacyFallbackOnlySelectsOnePendingRequest) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};

  ASSERT_TRUE(manager.add(pending_session("client-a"), "192.0.2.1", "request-a", now));
  auto only = manager.find_single_pending(now);
  ASSERT_TRUE(only);
  EXPECT_EQ(only.unique_id(), "client-a");
  only = {};

  ASSERT_TRUE(manager.add(pending_session("client-b"), "192.0.2.2", "request-b", now));
  EXPECT_FALSE(manager.find_single_pending(now));
}

TEST(PairingSessionManagerTest, RejectsDuplicateClientAndRequestIds) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};

  ASSERT_TRUE(manager.add(pending_session("client-a"), "192.0.2.1", "request-a", now));
  EXPECT_EQ(
    manager.add(pending_session("client-a"), "192.0.2.2", "request-b", now).status,
    pairing_session_manager_t::add_status_e::DUPLICATE_UNIQUE_ID
  );
  EXPECT_EQ(
    manager.add(pending_session("client-b"), "192.0.2.2", "request-a", now).status,
    pairing_session_manager_t::add_status_e::DUPLICATE_REQUEST_ID
  );
}

TEST(PairingSessionManagerTest, IdenticalSameSourceRetryReplacesOnlyPrePinLongPoll) {
  pairing_session_manager_t manager;
  const auto created = pairing_session_manager_t::time_point_t {};
  auto first_session = pending_session("client-a");
  first_session.client.cert = "bounded-certificate";
  first_session.async_insert_pin.salt = "00112233445566778899AABBCCDDEEFF";
  ASSERT_TRUE(manager.add(std::move(first_session), "192.0.2.1", "request-a", created));

  auto original = manager.find_pending_by_request_id("request-a", created);
  ASSERT_TRUE(original);
  ASSERT_TRUE(original.session().async_insert_pin.response.has_left());

  auto retry_session = pending_session("client-a");
  retry_session.client.cert = "bounded-certificate";
  retry_session.async_insert_pin.salt = "00112233445566778899AABBCCDDEEFF";
  const auto retry = manager.add(std::move(retry_session), "192.0.2.1", "unused-new-request-id", created + std::chrono::seconds {1});
  EXPECT_EQ(retry.status, pairing_session_manager_t::add_status_e::REPLACED);
  EXPECT_EQ(retry.request_id, "request-a");
  EXPECT_FALSE(original.session().async_insert_pin.response.has_left());
  original = {};

  auto active = manager.find_pending_by_request_id("request-a", created + std::chrono::seconds {1});
  ASSERT_TRUE(active);
  active.session().last_phase = PAIR_PHASE::GETSERVERCERT;
  active = {};

  auto active_retry = pending_session("client-a");
  active_retry.client.cert = "bounded-certificate";
  active_retry.async_insert_pin.salt = "00112233445566778899AABBCCDDEEFF";
  EXPECT_EQ(
    manager.add(std::move(active_retry), "192.0.2.1", "another-request-id", created + std::chrono::seconds {2}).status,
    pairing_session_manager_t::add_status_e::DUPLICATE_UNIQUE_ID
  );
}

TEST(PairingSessionManagerTest, RejectsOversizedOrMalformedStoredFields) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};

  auto oversized_id = pending_session(std::string(PAIRING_UNIQUE_ID_MAX_BYTES + 1, 'a'));
  EXPECT_EQ(
    manager.add(std::move(oversized_id), "192.0.2.1", "oversized-id", now).status,
    pairing_session_manager_t::add_status_e::INVALID_FIELDS
  );

  auto oversized_cert = pending_session("oversized-cert");
  oversized_cert.client.cert.assign(PAIRING_CLIENT_CERT_MAX_BYTES + 1, 'c');
  EXPECT_EQ(
    manager.add(std::move(oversized_cert), "192.0.2.1", "oversized-cert-request", now).status,
    pairing_session_manager_t::add_status_e::INVALID_FIELDS
  );

  auto oversized_salt = pending_session("oversized-salt");
  oversized_salt.async_insert_pin.salt.assign(PAIRING_SALT_HEX_BYTES + 1, '0');
  EXPECT_EQ(
    manager.add(std::move(oversized_salt), "192.0.2.1", "oversized-salt-request", now).status,
    pairing_session_manager_t::add_status_e::INVALID_FIELDS
  );
  EXPECT_EQ(manager.size(now), 0U);
}

TEST(PairingSessionManagerTest, ValidatesWireFieldBoundariesBeforeDecode) {
  EXPECT_EQ(PAIRING_REQUEST_BUFFER_LIMIT, 64U * 1024U);
  EXPECT_TRUE(is_valid_pairing_unique_id(std::string(PAIRING_UNIQUE_ID_MAX_BYTES, 'a')));
  EXPECT_FALSE(is_valid_pairing_unique_id(std::string(PAIRING_UNIQUE_ID_MAX_BYTES + 1, 'a')));
  EXPECT_FALSE(is_valid_pairing_unique_id(std::string("valid\0invalid", 13)));

  EXPECT_TRUE(is_valid_pairing_hex("00112233445566778899AABBCCDDEEFF", PAIRING_SALT_HEX_BYTES, PAIRING_SALT_HEX_BYTES));
  EXPECT_FALSE(is_valid_pairing_hex("00112233445566778899AABBCCDDEEF", PAIRING_SALT_HEX_BYTES, PAIRING_SALT_HEX_BYTES));
  EXPECT_FALSE(is_valid_pairing_hex("00112233445566778899AABBCCDDEEFG", PAIRING_SALT_HEX_BYTES, PAIRING_SALT_HEX_BYTES));
  EXPECT_TRUE(is_valid_pairing_hex(std::string(PAIRING_CLIENT_CERT_HEX_MAX_BYTES, 'A'), 2, PAIRING_CLIENT_CERT_HEX_MAX_BYTES));
  EXPECT_FALSE(is_valid_pairing_hex(std::string(PAIRING_CLIENT_CERT_HEX_MAX_BYTES + 2, 'A'), 2, PAIRING_CLIENT_CERT_HEX_MAX_BYTES));
}

TEST(PairingHttpBoundaryTest, RejectsRequestHeadersBeyondConfiguredCap) {
  SimpleWeb::Server<SimpleWeb::HTTP> server;
  server.config.port = 0;
  server.config.max_request_streambuf_size = PAIRING_REQUEST_BUFFER_LIMIT;
  server.config.timeout_request = 1;
  std::atomic<unsigned short> port {0};
  std::atomic<bool> rejected {false};
  server.on_error = [&](const auto &, const auto &) {
    rejected = true;
  };
  server.resource["^/pair$"]["GET"] = [](const auto &response, const auto &) {
    response->write("ok");
  };

  std::jthread server_thread([&] {
    server.start([&](unsigned short assigned_port) {
      port = assigned_port;
    });
  });
  for (int wait = 0; wait < 100 && port == 0; ++wait) {
    std::this_thread::sleep_for(std::chrono::milliseconds {10});
  }
  ASSERT_NE(port.load(), 0);

  SimpleWeb::Client<SimpleWeb::HTTP> client {std::format("localhost:{}", port.load())};
  client.config.timeout = 2;
  try {
    client.request("GET", "/pair?oversized=" + std::string(PAIRING_REQUEST_BUFFER_LIMIT, 'A'));
  } catch (const std::exception &) {
  }
  for (int wait = 0; wait < 100 && !rejected; ++wait) {
    std::this_thread::sleep_for(std::chrono::milliseconds {10});
  }

  server.stop();
  server_thread.join();
  EXPECT_TRUE(rejected.load());
}

TEST(PairingSessionManagerTest, ExpiresAtExactlyTwoMinutes) {
  pairing_session_manager_t manager;
  const auto created = pairing_session_manager_t::time_point_t {};

  ASSERT_TRUE(manager.add(pending_session("client-a"), "192.0.2.1", "request-a", created));
  EXPECT_EQ(manager.cleanup_expired(created + pairing_session_manager_t::SESSION_TTL - std::chrono::milliseconds {1}), 0U);
  EXPECT_EQ(manager.size(created + pairing_session_manager_t::SESSION_TTL - std::chrono::milliseconds {1}), 1U);
  auto retained = manager.find_pending_by_request_id("request-a", created);
  ASSERT_TRUE(retained);
  ASSERT_TRUE(retained.session().async_insert_pin.response.has_left());
  EXPECT_EQ(manager.cleanup_expired(created + pairing_session_manager_t::SESSION_TTL), 1U);
  EXPECT_FALSE(retained.session().async_insert_pin.response.has_left());
  EXPECT_FALSE(retained.session().async_insert_pin.response.has_right());
  EXPECT_EQ(manager.size(created + pairing_session_manager_t::SESSION_TTL), 0U);
  EXPECT_FALSE(manager.find_pending_by_request_id("request-a", created + pairing_session_manager_t::SESSION_TTL));
}

TEST(PairingSessionManagerTest, CancellationReleasesHeldResponse) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};

  ASSERT_TRUE(manager.add(pending_session("client-a"), "192.0.2.1", "request-a", now));
  auto retained = manager.find_pending_by_request_id("request-a", now);
  ASSERT_TRUE(retained);
  ASSERT_TRUE(retained.session().async_insert_pin.response.has_left());

  EXPECT_TRUE(manager.cancel_by_request_id("request-a"));
  EXPECT_FALSE(retained.session().async_insert_pin.response.has_left());
  EXPECT_FALSE(retained.session().async_insert_pin.response.has_right());
  EXPECT_EQ(manager.size(now), 0U);
  EXPECT_FALSE(manager.cancel_by_request_id("request-a"));
}

TEST(PairingSessionManagerTest, EnforcesThreePinAttemptLimit) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};

  ASSERT_TRUE(manager.add(pending_session("client-a"), "192.0.2.1", "request-a", now));
  auto stored = manager.find_pending_by_request_id("request-a", now);
  ASSERT_TRUE(stored);
  EXPECT_EQ(manager.record_pin_attempt(stored, now), pairing_session_manager_t::pin_attempt_status_e::ACCEPTED);
  EXPECT_EQ(manager.record_pin_attempt(stored, now), pairing_session_manager_t::pin_attempt_status_e::ACCEPTED);
  EXPECT_EQ(manager.record_pin_attempt(stored, now), pairing_session_manager_t::pin_attempt_status_e::SESSION_EXHAUSTED);
  EXPECT_EQ(manager.record_pin_attempt(stored, now), pairing_session_manager_t::pin_attempt_status_e::SOURCE_RATE_LIMITED);
}

TEST(PairingSessionManagerTest, BindsHandshakeLookupToOriginalSource) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};

  ASSERT_TRUE(manager.add(pending_session("client-a"), "192.0.2.1", "request-a", now));
  auto matching = manager.find_by_unique_id("client-a", "192.0.2.1", now);
  ASSERT_TRUE(matching);
  EXPECT_EQ(matching.source(), "192.0.2.1");
  matching = {};
  EXPECT_FALSE(manager.find_by_unique_id("client-a", "192.0.2.2", now));
}

TEST(PairingSessionManagerTest, SourceBudgetSurvivesSessionCyclingAndExpires) {
  pairing_session_manager_t manager;
  const auto created = pairing_session_manager_t::time_point_t {};

  for (std::size_t index = 0; index < pairing_session_manager_t::MAX_PIN_ATTEMPTS; ++index) {
    const auto client = "client-" + std::to_string(index);
    const auto request = "request-" + std::to_string(index);
    ASSERT_TRUE(manager.add(pending_session(client), "192.0.2.1", request, created));
    auto stored = manager.find_pending_by_request_id(request, created);
    ASSERT_TRUE(stored);
    EXPECT_EQ(manager.record_pin_attempt(stored, created), pairing_session_manager_t::pin_attempt_status_e::ACCEPTED);
    stored = {};
    manager.erase(client);
  }

  EXPECT_EQ(
    manager.add(
             pending_session("blocked-client"),
             "192.0.2.1",
             "blocked-request",
             created + pairing_session_manager_t::SESSION_TTL - std::chrono::milliseconds {1}
    )
      .status,
    pairing_session_manager_t::add_status_e::SOURCE_LIMIT
  );
  EXPECT_TRUE(manager.add(
    pending_session("allowed-client"),
    "192.0.2.1",
    "allowed-request",
    created + pairing_session_manager_t::SESSION_TTL
  ));
}

TEST(PairingSessionManagerTest, CloseAtomicallyRejectsLateAdmissions) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};
  std::vector<std::jthread> threads;

  for (std::size_t index = 0; index < pairing_session_manager_t::MAX_GLOBAL_SESSIONS; ++index) {
    threads.emplace_back([&, index] {
      manager.add(
        pending_session("client-" + std::to_string(index)),
        "198.51.100." + std::to_string(index),
        "request-" + std::to_string(index),
        now
      );
    });
  }
  threads.emplace_back([&] {
    manager.close();
  });
  threads.clear();

  EXPECT_FALSE(manager.accepting());
  EXPECT_EQ(manager.size(now), 0U);
  EXPECT_EQ(
    manager.add(pending_session("late-client"), "203.0.113.1", "late-request", now).status,
    pairing_session_manager_t::add_status_e::CLOSED
  );
}

TEST(PairingSessionManagerTest, EnforcesPerSourceAndGlobalCaps) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};

  for (std::size_t index = 0; index < pairing_session_manager_t::MAX_SESSIONS_PER_SOURCE; ++index) {
    ASSERT_TRUE(manager.add(pending_session("shared-" + std::to_string(index)), "192.0.2.1", "shared-request-" + std::to_string(index), now));
  }
  EXPECT_EQ(
    manager.add(pending_session("source-overflow"), "192.0.2.1", "source-overflow-request", now).status,
    pairing_session_manager_t::add_status_e::SOURCE_LIMIT
  );

  for (std::size_t index = pairing_session_manager_t::MAX_SESSIONS_PER_SOURCE; index < pairing_session_manager_t::MAX_GLOBAL_SESSIONS; ++index) {
    ASSERT_TRUE(manager.add(
      pending_session("global-" + std::to_string(index)),
      "198.51.100." + std::to_string(index),
      "global-request-" + std::to_string(index),
      now
    ));
  }
  EXPECT_EQ(
    manager.add(pending_session("global-overflow"), "203.0.113.1", "global-overflow-request", now).status,
    pairing_session_manager_t::add_status_e::GLOBAL_LIMIT
  );
}

TEST(PairingSessionManagerTest, ConcurrentAddsRemainBounded) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};
  std::atomic<std::size_t> added {0};
  std::vector<std::jthread> threads;

  for (std::size_t index = 0; index < pairing_session_manager_t::MAX_GLOBAL_SESSIONS * 2; ++index) {
    threads.emplace_back([&, index] {
      if (manager.add(
            pending_session("client-" + std::to_string(index)),
            "203.0.113." + std::to_string(index),
            "request-" + std::to_string(index),
            now
          )) {
        ++added;
      }
    });
  }
  threads.clear();

  EXPECT_EQ(added.load(), pairing_session_manager_t::MAX_GLOBAL_SESSIONS);
  EXPECT_EQ(manager.size(now), pairing_session_manager_t::MAX_GLOBAL_SESSIONS);
}

TEST(PairingSessionManagerTest, ConcurrentMaximumSizeSessionsRemainMemoryBounded) {
  pairing_session_manager_t manager;
  const auto now = pairing_session_manager_t::time_point_t {};
  std::vector<std::jthread> threads;

  for (std::size_t index = 0; index < pairing_session_manager_t::MAX_GLOBAL_SESSIONS * 2; ++index) {
    threads.emplace_back([&, index] {
      auto session = pending_session("large-client-" + std::to_string(index));
      session.client.cert.assign(PAIRING_CLIENT_CERT_MAX_BYTES, 'c');
      manager.add(
        std::move(session),
        "203.0.113." + std::to_string(index),
        "large-request-" + std::to_string(index),
        now
      );
    });
  }
  threads.clear();

  EXPECT_EQ(manager.size(now), pairing_session_manager_t::MAX_GLOBAL_SESSIONS);
  EXPECT_LE(
    manager.size(now) * PAIRING_CLIENT_CERT_MAX_BYTES,
    pairing_session_manager_t::MAX_GLOBAL_SESSIONS * PAIRING_CLIENT_CERT_MAX_BYTES
  );
}
